name: Auto-Update from ChatGPT

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Allows the workflow to commit changes

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          if [ -f backend/requirements.txt ]; then
            pip install -r backend/requirements.txt
          fi

      - name: Configure Git
        run: |
          git config --global user.email "chatgpt-bot@example.com"
          git config --global user.name "ChatGPT Auto-Commit"

      - name: Commit & Push Changes
        run: |
          git add .
          git commit -m "Auto-update from ChatGPT" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
