name: Auto-Update from ChatGPT

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Ensures GitHub Actions has write access to push changes

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Fixes permission issues

      - name: Set Up Git
        run: |
         
